% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{section}{-1}
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaklines,
  commandchars=\\\{\}

\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={QRM II Graded Assignment (11), Period 1 2025},
  pdfauthor={Fill in your group number and names here},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{QRM II Graded Assignment (11), Period 1 2025}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Material by Sjoerd van Alten and Klervie Toczé}
\author{Fill in your group number and names here}
\date{25-09-2025}

\begin{document}
\maketitle

\section{Introduction}\label{introduction}

This assignment is to be completed in groups of 3-4. Further, all
students in your group need to be assigned to the same R tutorial group
(Friday's tutorial). You can sign yourself up for a group on Canvas.
Please do so
\textbf{before the start of your first R tutorial on Friday September 5th.}
You can use the Discussion Board in Canvas if you do not have a group
yet or if your group is incomplete.

The assignment has 5 parts, and each part corresponds to the course
material of that week (with the exclusion of week 6, for which there is
no R programming material).

You are supposed to hand in these assignments on Canvas at the following
dates:

\begin{itemize}
\tightlist
\item
  \textbf{Deadline 1} \emph{Thursday September 25th, at 23:59pm}: you
  are supposed to hand in weeks 1, 2, and 3 of this assignment. This
  will determine 18\% of your overall course grade
\item
  \textbf{Deadline 2} \emph{Thursday October 9th, at 23:59pm}: you are
  supposed to hand in weeks 4, and 5 of this assignment. This will
  determine 12\% of your overall course grade
\end{itemize}

The R tutorials (each Friday) will consist of two halves. During the
first half, you will discuss the tutorial exercises. These can be
downloaded separately from Canvas. During the second half, you can work
on this graded assignment within your own group. The purpose is that you
find out how to work with R for doing statistical analyses by yourself.
The tutorial exercises are meant to teach you basic commands to get you
started, but to answer the problem sets in this assignment, you might
need to research your own solutions, and use functions and commands not
described in the tutorial exercises. Learning how to solve your own
research problems is integral part of learning R. When you and your
group get stuck on how to approach an exercise, the hierarchy in finding
your way is as follows:

\begin{itemize}
\tightlist
\item
  use the concepts from the tutorial exercises;
\item
  use the cheat sheets available on Canvas;
\item
  use Google, YouTube, StackOverflow, or another website;
\item
  ask the teacher.
\end{itemize}

The use of generative AI is \textbf{not} permitted and may result in a
grade of 0. See the AI protocol in the course manual for details.

To answer the assignment, you can simply fill out this R markdown
document. There are designated places which you can fill with R code.
There are also designated spaces for you to answer each question. Often,
the structure of an answer will be as follows. First, you type the R
code in the designated box. This will show how you analyzed the data to
get the answer to the question. Below the box for the R code, you will
then summarize your answer to the question, i.e.~what are the
conclusions that you draw from the data analysis?

When handing in, you are supposed to submit this .Rmd file, and a
knitted version of this document. You can knit this document to pdf,
word, or html. Knitting to pdf requires you to have a .tex distribution
installed on your computer. Knitting to Word requires you to have Word
installed.

The exercises are designed such that you should be able to finish the
majority of them during the tutorial each week. If you are not able to
finish them fully during that time, you are expected to work on it in
your own time using the computers on campus or your own device. It is
best to meet as a group in-person when working together. If you want to
work remotely, github is a good platform to guarantee smooth
collaboration. Alternatively, you can email this .Rmd file back and
forth to one another as a group, but this is not recommended as it is
more cumbersome.

We encourage you to keep your code blocks, printing statements, and
final answers, as short as possible. In any case, there is a page limit
of 6 pages per week, which encompasses the total length of this document
which consists of the questions, your coding lines, and your answers.
When your answers to questions of the respective week exceed this page
limit, they will not be graded, resulting in zero points.

Each week consists of 1, 2, or 3 subquestions. The total amount of
points you can earn per week is 20 points.

\section{Week 1}\label{week-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the dataset ``movies4.tsv'' on Canvas. Describe your data set:
  How many observations does it have. How many variables are there? How
  many subjects? What consists of a subject? \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#install.packages("readr")}
\CommentTok{\#install.packages("tidyverse")}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'readr' was built under R version 4.5.1
\end{verbatim}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.1
## v ggplot2   3.5.2     v tibble    3.2.1
## v lubridate 1.9.4     v tidyr     1.3.1
## v purrr     1.0.4     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\NormalTok{movies4 }\OtherTok{=} \FunctionTok{read\_tsv}\NormalTok{(}\StringTok{"movies4.tsv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 808 Columns: 19
## -- Column specification --------------------------------------------------------
## Delimiter: "\t"
## chr   (8): keywords, original_language, title, genre, first_actor, first_act...
## dbl  (10): index, budget, popularity, revenue, runtime, vote_average, vote_c...
## date  (1): release_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(index)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 808 x 2
##    index     n
##    <dbl> <int>
##  1     1     1
##  2     7     1
##  3    16     1
##  4    20     1
##  5    26     1
##  6    29     1
##  7    33     1
##  8    37     1
##  9    42     1
## 10    46     1
## # i 798 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 808 x 19
##    index budget keywords original_language title popularity release_date revenue
##    <dbl>  <dbl> <chr>    <chr>             <chr>      <dbl> <date>         <dbl>
##  1  2256 0      <NA>     en                The ~      0.286 2012-08-29    0     
##  2  2473 1.5 e7 barcelo~ en                Vick~     32.8   2008-08-15    9.64e7
##  3  1514 3.20e7 gunslin~ en                The ~     16.5   1995-02-09    1.86e7
##  4  1512 3.20e7 robbery~ en                A Hi~     34.6   2005-09-23    6.07e7
##  5   395 8.5 e7 holiday~ en                The ~     45.0   2006-12-08    1.94e8
##  6  3156 0      1970s h~ en                Red ~      5.50  2011-08-04    0     
##  7  4753 6   e4 haunted~ en                Hayr~      0.412 2012-10-13    0     
##  8  4590 0      kidnapp~ en                Show~      0.231 2004-09-23    0     
##  9  1665 0      venice ~ en                The ~     12.5   2004-09-03    0     
## 10  2714 1.4 e7 new yor~ en                Marg~      4.90  2011-09-30    4.65e4
## # i 798 more rows
## # i 11 more variables: runtime <dbl>, vote_average <dbl>, vote_count <dbl>,
## #   genre <chr>, release_year <dbl>, release_month <dbl>, release_day <dbl>,
## #   first_actor <chr>, first_actor_gender <chr>, director_first_name <chr>,
## #   director_gender <chr>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#808 observations}
\CommentTok{\#19 variables}
\CommentTok{\#19 subjects}
\CommentTok{\#A subject consists of a multitude of information about a movie, from the title to the release year to the head actor to the vote average.}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your response here.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Which of the following types of variables are present in your data
  set? (i) nominal; (ii) ordinal; (iii); interval; (iv) ratio. If
  present, name one example of such a variable present in your data set.
  \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Nominal variables: keywords, original\_language, title, genre, first\_actor, first\_actor\_gender, director\_first\_name, director\_gender}

\CommentTok{\#Ordinal variables: NA}

\CommentTok{\#Interval variables: index, release\_date, release\_year, release\_month, release\_day}

\CommentTok{\#Ratio variables: budget, popularity, revenue, runtime, vote\_average, vote\_count }
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:} Nominal variables: keywords, original\_language,
title, genre, first\_actor, first\_actor\_gender, director\_first\_name,
director\_gender

Ordinal variables: NA

Interval variables: index, release\_date, release\_year, release\_month,
release\_day

Ratio variables: budget, popularity, revenue, runtime, vote\_average,
vote\_count

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  A movie studio wants to know which types of movies give maximal
  profit. Perform the following steps to provide the movie studio with
  an analysis which corresponds to their request:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create the variable profits as the revenue of a movie minus its
  budget. Report its mean, median, maximum, and minimum.
  \textbf{[2 points]}
\item
  Which movie has the highest profits in your data set and how much are
  these profits. Which movie has the lowest and how much are its
  profits? If multiple movies have the exact same highest or lowest
  profits, give only one example. \textbf{[2 points]}
\item
  Create a boxplot of the variable profits. Make sure it has an
  appropriate title, and appropriate titles and labels for the x- and
  y-axis. Give Q1, Q2, Q3, and Q4. What does this tell you about the
  nature of making money in the movies industry? \textbf{[2 points]}
\item
  Add a new variable to your data set the log of profits. When creating
  this variable, what happens to movies for which profits is zero or
  negative? What then happens when you calculate the mean of log of
  profits? \textbf{[2 points]}
\item
  For movies that have a profit of zero or less, replace log of profits
  with ``NA''. What is now the mean of log of profits? Create a boxplot
  for log of profits, again with an appropriate title, x- and y-axis
  labels. How does it compare to the boxplot you made under c.)?
  \textbf{[2 points]}
\item
  Create a scatterplot of with the runtime of movies on the x-axis and
  the average vote of movies on the y-axis. What do you conclude from
  the scatterplot? Are movies with a longer runtime considered worse or
  better by the audience, or does the audience not have a preference?
  Why do you think this is the case? \textbf{[2 points]}
\end{enumerate}

For each step, you should provide first all the code you used to answer
the question and then formulate an answer using full sentences.

\emph{Step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\OtherTok{=} \FunctionTok{read\_tsv}\NormalTok{(}\StringTok{"movies4.tsv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 808 Columns: 19
## -- Column specification --------------------------------------------------------
## Delimiter: "\t"
## chr   (8): keywords, original_language, title, genre, first_actor, first_act...
## dbl  (10): index, budget, popularity, revenue, runtime, vote_average, vote_c...
## date  (1): release_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\OtherTok{=}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{profits=}\NormalTok{revenue}\SpecialCharTok{{-}}\NormalTok{budget)}

\NormalTok{profit\_summary }\OtherTok{=}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_profit=}\FunctionTok{mean}\NormalTok{(profits, }\AttributeTok{na.rm=}\NormalTok{T),}
            \AttributeTok{median\_profit=}\FunctionTok{median}\NormalTok{(profits, }\AttributeTok{na.rm=}\NormalTok{T),}
            \AttributeTok{max\_profit=}\FunctionTok{max}\NormalTok{(profits, }\AttributeTok{na.rm=}\NormalTok{T),}
            \AttributeTok{min\_profit=}\FunctionTok{min}\NormalTok{(profits, }\AttributeTok{na.rm=}\NormalTok{T)}
\NormalTok{            )}
\NormalTok{profit\_summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 4
##   mean_profit median_profit max_profit min_profit
##         <dbl>         <dbl>      <dbl>      <dbl>
## 1   52885669.             0 1299557910 -150000000
\end{verbatim}

\textbf{Your Answer:}

mean\_profit = 52885669 median\_profit = 0 max\_profit = 1299557910
min\_profit = -1.5e+08

\emph{Step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\OtherTok{=} \FunctionTok{read\_tsv}\NormalTok{(}\StringTok{"movies4.tsv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 808 Columns: 19
## -- Column specification --------------------------------------------------------
## Delimiter: "\t"
## chr   (8): keywords, original_language, title, genre, first_actor, first_act...
## dbl  (10): index, budget, popularity, revenue, runtime, vote_average, vote_c...
## date  (1): release_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\OtherTok{=}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{profits=}\NormalTok{revenue}\SpecialCharTok{{-}}\NormalTok{budget)}

\NormalTok{movies4\_highest }\OtherTok{=}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(profits}\SpecialCharTok{==}\FunctionTok{max}\NormalTok{(profits, }\AttributeTok{na.rm=}\NormalTok{T))}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(title, profits)}
\NormalTok{movies4\_highest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   title           profits
##   <chr>             <dbl>
## 1 The Avengers 1299557910
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4\_lowest }\OtherTok{=}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(profits}\SpecialCharTok{==}\FunctionTok{min}\NormalTok{(profits, }\AttributeTok{na.rm=}\NormalTok{T))}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(title, profits)}
\NormalTok{movies4\_lowest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   title          profits
##   <chr>            <dbl>
## 1 The Wolfman -150000000
\end{verbatim}

\textbf{Your Answer:}

Highest profits: The Avengers, profits=1299557910 Lowest profits: The
wolfman, profits=-1.5e+08 (-\$150 million)

\emph{Step c}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{ (ggplot2)}

\NormalTok{boxplot\_profits}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(movies4, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ title, }\AttributeTok{y =}\NormalTok{ profits)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Movie Profits"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Profit"}\NormalTok{)}
\NormalTok{boxplot\_profits}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-5-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{quartiles }\OtherTok{=} \FunctionTok{quantile}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{profits)}
\NormalTok{quartiles}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         0%        25%        50%        75%       100% 
## -150000000   -1849854          0   49711134 1299557910
\end{verbatim}

\textbf{Your Answer:}

Q1: -1849854 Q2: 0 Q3: 49711134 Q4: 12999557910

This shows that making money in the movies industry is risky, as the
bottom 50\% is in loss or break even, while the top 25\% is in massive
profits.

\emph{Step d}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\OtherTok{=} \FunctionTok{read\_tsv}\NormalTok{(}\StringTok{"movies4.tsv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 808 Columns: 19
## -- Column specification --------------------------------------------------------
## Delimiter: "\t"
## chr   (8): keywords, original_language, title, genre, first_actor, first_act...
## dbl  (10): index, budget, popularity, revenue, runtime, vote_average, vote_c...
## date  (1): release_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\OtherTok{=}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{profits=}\NormalTok{revenue}\SpecialCharTok{{-}}\NormalTok{budget)}
\NormalTok{movies4 }\OtherTok{=}\NormalTok{movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{log\_profits=}\FunctionTok{log}\NormalTok{(profits))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: There was 1 warning in `mutate()`.
## i In argument: `log_profits = log(profits)`.
## Caused by warning in `log()`:
## ! NaNs produced
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\FunctionTok{mean}\NormalTok{(log\_profits, }\AttributeTok{na.rm=}\NormalTok{T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   `mean(log_profits, na.rm = T)`
##                            <dbl>
## 1                           -Inf
\end{verbatim}

\textbf{Your Answer:}

Where profit is 0, the log is -inf.

Where profit is negative, the log is NaN

The mean results in NaN, and the mean with na.rm=T results in -inf

\emph{Step e}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4}\OtherTok{=}\FunctionTok{read\_tsv}\NormalTok{(}\StringTok{"movies4.tsv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 808 Columns: 19
## -- Column specification --------------------------------------------------------
## Delimiter: "\t"
## chr   (8): keywords, original_language, title, genre, first_actor, first_act...
## dbl  (10): index, budget, popularity, revenue, runtime, vote_average, vote_c...
## date  (1): release_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4}\OtherTok{=}\NormalTok{movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{profits=}\NormalTok{revenue}\SpecialCharTok{{-}}\NormalTok{budget)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{log\_profits =} \FunctionTok{ifelse}\NormalTok{(profits }\SpecialCharTok{\textless{}=} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(profits)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: There was 1 warning in `mutate()`.
## i In argument: `log_profits = ifelse(profits <= 0, NA, log(profits))`.
## Caused by warning in `log()`:
## ! NaNs produced
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 808 x 21
##    index budget keywords original_language title popularity release_date revenue
##    <dbl>  <dbl> <chr>    <chr>             <chr>      <dbl> <date>         <dbl>
##  1  2256 0      <NA>     en                The ~      0.286 2012-08-29    0     
##  2  2473 1.5 e7 barcelo~ en                Vick~     32.8   2008-08-15    9.64e7
##  3  1514 3.20e7 gunslin~ en                The ~     16.5   1995-02-09    1.86e7
##  4  1512 3.20e7 robbery~ en                A Hi~     34.6   2005-09-23    6.07e7
##  5   395 8.5 e7 holiday~ en                The ~     45.0   2006-12-08    1.94e8
##  6  3156 0      1970s h~ en                Red ~      5.50  2011-08-04    0     
##  7  4753 6   e4 haunted~ en                Hayr~      0.412 2012-10-13    0     
##  8  4590 0      kidnapp~ en                Show~      0.231 2004-09-23    0     
##  9  1665 0      venice ~ en                The ~     12.5   2004-09-03    0     
## 10  2714 1.4 e7 new yor~ en                Marg~      4.90  2011-09-30    4.65e4
## # i 798 more rows
## # i 13 more variables: runtime <dbl>, vote_average <dbl>, vote_count <dbl>,
## #   genre <chr>, release_year <dbl>, release_month <dbl>, release_day <dbl>,
## #   first_actor <chr>, first_actor_gender <chr>, director_first_name <chr>,
## #   director_gender <chr>, profits <dbl>, log_profits <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\FunctionTok{mean}\NormalTok{(log\_profits, }\AttributeTok{na.rm=}\NormalTok{T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   `mean(log_profits, na.rm = T)`
##                            <dbl>
## 1                           17.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(movies4, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{log\_profits)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 407 rows containing non-finite outside the scale range
## (`stat_boxplot()`).
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-7-1.pdf}}

\textbf{Your Answer:}

Mean of log of profits = 17.33131

This boxplot seems to have less extreme outliers.

\emph{Step f}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(movies4, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{runtime, }\AttributeTok{y=}\NormalTok{vote\_average)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-8-1.pdf}}

\textbf{Your Answer:}

There seems to be a slight correlation between runtime and higher
average votes, as the points at the relatively shorter runtime of 100
are more dense around the 5.0 to 7.0 ratings, while the point at the
relatively longer runtime of 125 to 150 minutes seem to be more dense
around the 6.5 to 7.5 range.

\section{Week 2}\label{week-2}

1 Is your dataset movies4.tsv the full population, or is it a sample of
a larger population? If the latter, how would you describe the full
population? \textbf{[4 points]}

The dataset is a sample of a larger population. It does not represent
the full population of movies. The full population would consist of all
movies released worldwide, covering a wide variety of genres, budgets,
release years, and popularity levels.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  For which actor in your data set do you observe the most movies?
  \textbf{[2 points]}
\item
  What is the average revenue of the movie in which this actor plays and
  does the revenue lie above or below the revenue of an average movie
  according to your data set? \textbf{[2 points]}\\
\item
  How trustworthy do you consider your conclusion to answer 2b? Use the
  term ``law of large numbers'' in your explanation. \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{library}\NormalTok{(tidyverse)}

\NormalTok{y}\OtherTok{\textless{}{-}}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(first\_actor)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(first\_actor)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(n))}

\FunctionTok{head}\NormalTok{(y,}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 2
## # Groups:   first_actor [2]
##   first_actor           n
##   <chr>             <int>
## 1 Bruce Willis          9
## 2 Denzel Washington     8
\end{verbatim}

\textbf{Your Answer:} Bruce Willis is the actor who plays in the most
movies in the data set. We pulled the top 2 rows to confirm that there
is not any other actor with the same amount of movies.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{z}\OtherTok{\textless{}{-}}\NormalTok{ movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(first\_actor)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_r =} \FunctionTok{mean}\NormalTok{(revenue, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\NormalTok{z }\OtherTok{=} \FunctionTok{slice}\NormalTok{(z, }\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{64}\NormalTok{))}
\FunctionTok{head}\NormalTok{(z,}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   first_actor      mean_r
##   <chr>             <dbl>
## 1 Bruce Willis 255652124.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_revenue }\OtherTok{=} \FunctionTok{mean}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{revenue)}
\NormalTok{mean\_revenue}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 82727885
\end{verbatim}

The avarage revenue of Bruce Willis is 255652124 this lies above the
average revenue of 82727855

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(y}\SpecialCharTok{$}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.453237
\end{verbatim}

According to the law of large numbers, a higher number of observations
leads to a more accurate estimate. Since Bruce Willis has a relatively
high number of observations (9 movies, compared to an average of 1.45
movies for other actors), our conclusion from 2b can be considered quite
trustworthy.

3 For this question, you will assume that your data set is the full
population.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Recode profits such that it is expressed in millions. What is the
  variance of the variable profits (in millions) in your data set?
  \textbf{[2 points]}
\item
  Create a new data set, called movies\_sample. Make sure that it is a
  random sample of your data set of 25 movies. What is the variance of
  profits in this random sample? How does it compare to the variance of
  profits in 2a? \textbf{[2 points]}
\item
  In a for loop, create 100 different samples of 25 movies, as in b, and
  estimate the variance within each sample. Save the variance of each
  sample in a vector called sample\_vars. So the first position of the
  vector would have the variance of the first sample, the second
  position the variance of the second sample, etc. Print the start of
  this vector. \textbf{[2 points]}
\item
  Summarize and make a histogram of sample\_vars. What is the mean,
  standard deviation and shape of its distribution? \textbf{[2 points]}
\item
  In your opinion, is a sample of 25 movies sufficient to get a reliable
  estimate of the population variance of profits, using the sample
  variance? Explain? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}

\NormalTok{movies4 }\OtherTok{\textless{}{-}}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{profit\_in\_millions =}\NormalTok{ profits }\SpecialCharTok{/} \DecValTok{1000000}\NormalTok{)}

\NormalTok{variance }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{profit\_in\_millions)}

\NormalTok{variance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20270.56
\end{verbatim}

\textbf{Your Answer:}

The variance of the profit in millions in the data set is 20270.56
million.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{56564}\NormalTok{)}
\NormalTok{movies\_sample }\OtherTok{\textless{}{-}}\NormalTok{ movies4[}\FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(movies4), }\DecValTok{25}\NormalTok{), ]}

\NormalTok{variance\_sample }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(movies\_sample}\SpecialCharTok{$}\NormalTok{profit\_in\_millions)}

\NormalTok{variance\_sample}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 29823.65
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{variance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20270.56
\end{verbatim}

\textbf{Your Answer:}

The variance of the sample is significantly higher than in the original
data set. This because the random sample is less precise.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{293}\NormalTok{)}
\NormalTok{sample\_vars}\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{100}\NormalTok{)\{}
\NormalTok{  mov\_samp}\OtherTok{\textless{}{-}} \FunctionTok{slice\_sample}\NormalTok{(movies4, }\AttributeTok{n=}\DecValTok{25}\NormalTok{)}
\NormalTok{  sample\_vars[i]}\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(mov\_samp}\SpecialCharTok{$}\NormalTok{profit\_in\_millions)}
  
\NormalTok{\}}
\FunctionTok{print}\NormalTok{(sample\_vars[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{9}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 37056.903  9338.942  2122.148 69705.140 11612.124 24541.473 49198.948
## [8]  7123.823  3566.988
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{min}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1598.791
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{max}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 73529.14
\end{verbatim}

\textbf{Your Answer:}

In the different variances of the samples we took you can see a very big
difference, the lowest value in the vector is 1598.8 million and the
highest variance is 73529.1 million.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(sample\_vars)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{mean}\NormalTok{(sample\_vars),}
              \AttributeTok{col =} \StringTok{"red"}\NormalTok{,}
              \AttributeTok{lwd =} \DecValTok{3}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{sd}\NormalTok{(sample\_vars),}
       \AttributeTok{col=}\StringTok{"blue"}\NormalTok{,}
       \AttributeTok{lwd =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-15-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"mean = "}\NormalTok{, }\FunctionTok{mean}\NormalTok{(sample\_vars), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mean =  19923.88
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"standard deviation ="}\NormalTok{,}\FunctionTok{sd}\NormalTok{(sample\_vars))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## standard deviation = 18251.93
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19923.88
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 18251.93
\end{verbatim}

\textbf{Your Answer:}

In the histogram you can see that the variances of the samples are not
normal distributed, and that there are more low values than higher ones.
This principles is called right-skewed, meaning that most of the
variances are low and a few variances have a way higher variance. The
mean of the variances is: 19923.88 million, and the standard deviation
is 18251.93 million

\emph{step e}

\textbf{Your Answer:}

Since the variances vary a lot, this shows that estimates depend greatly
on which movies are chosen. so a sample size of 25 is not enough to get
reliable estimates

\textbf{Your answer here}

\section{Week 3}\label{week-3}

For the next part of the assignment, assume that the movies in your data
frame are a random sample of a larger population of movies.

1

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new data set that only includes movies that are of the genre
  ``Thriller''. For these thriller movies, give a 99 percent confidence
  interval for the variable \emph{runtime}. Interpret the result.
  \textbf{[2 points]}
\item
  Now, assume that the variance of \emph{runtime} amongst thriller
  movies in your data is exactly the same as the variance of
  \emph{runtime} in the population. Under this assumption, give a 99
  percent confidence interval for the variable \emph{runtime} among
  thriller movies. Interpret the result. Is you confidence interval
  wider or less wide than the one you found under question 1a? Why is
  that the case? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(readr)}
\NormalTok{movies4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 808 x 22
##    index budget keywords original_language title popularity release_date revenue
##    <dbl>  <dbl> <chr>    <chr>             <chr>      <dbl> <date>         <dbl>
##  1  2256 0      <NA>     en                The ~      0.286 2012-08-29    0     
##  2  2473 1.5 e7 barcelo~ en                Vick~     32.8   2008-08-15    9.64e7
##  3  1514 3.20e7 gunslin~ en                The ~     16.5   1995-02-09    1.86e7
##  4  1512 3.20e7 robbery~ en                A Hi~     34.6   2005-09-23    6.07e7
##  5   395 8.5 e7 holiday~ en                The ~     45.0   2006-12-08    1.94e8
##  6  3156 0      1970s h~ en                Red ~      5.50  2011-08-04    0     
##  7  4753 6   e4 haunted~ en                Hayr~      0.412 2012-10-13    0     
##  8  4590 0      kidnapp~ en                Show~      0.231 2004-09-23    0     
##  9  1665 0      venice ~ en                The ~     12.5   2004-09-03    0     
## 10  2714 1.4 e7 new yor~ en                Marg~      4.90  2011-09-30    4.65e4
## # i 798 more rows
## # i 14 more variables: runtime <dbl>, vote_average <dbl>, vote_count <dbl>,
## #   genre <chr>, release_year <dbl>, release_month <dbl>, release_day <dbl>,
## #   first_actor <chr>, first_actor_gender <chr>, director_first_name <chr>,
## #   director_gender <chr>, profits <dbl>, log_profits <dbl>,
## #   profit_in_millions <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies\_thriller }\OtherTok{\textless{}{-}}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(genre}\SpecialCharTok{==}\StringTok{"Thriller"}\NormalTok{)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n=}\FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_runtime=}\FunctionTok{mean}\NormalTok{(runtime, }\AttributeTok{na.rm=}\NormalTok{T),}
    \AttributeTok{sd\_runtime=}\FunctionTok{sd}\NormalTok{(runtime, }\AttributeTok{na.rm=}\NormalTok{T),}
    \AttributeTok{se=}\NormalTok{sd\_runtime}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{n}\NormalTok{()),}
    \AttributeTok{t\_critical=}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.995}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{),}
    \AttributeTok{ci\_lower=}\NormalTok{mean\_runtime}\SpecialCharTok{{-}}\NormalTok{t\_critical}\SpecialCharTok{*}\NormalTok{se,}
    \AttributeTok{ci\_upper=}\NormalTok{mean\_runtime}\SpecialCharTok{+}\NormalTok{t\_critical}\SpecialCharTok{*}\NormalTok{se)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{print}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 7
##       n mean_runtime sd_runtime    se t_critical ci_lower ci_upper
##   <int>        <dbl>      <dbl> <dbl>      <dbl>    <dbl>    <dbl>
## 1   116         105.       19.2  1.78       2.62     101.     110.
\end{verbatim}

\textbf{Your Answer:}

According to this 99\% confidence interval, the runtime of the movies in
the Thriller genre is reasonably consistent, as the confidence interval
is pretty narrow, going from 100.55 to 109.90.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies4 }\OtherTok{\textless{}{-}}\NormalTok{ movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{runtime =} \FunctionTok{ifelse}\NormalTok{(runtime }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, runtime))}

\NormalTok{movies\_thrillerb }\OtherTok{\textless{}{-}}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(genre }\SpecialCharTok{==} \StringTok{"Thriller"}\NormalTok{)}

\NormalTok{mean\_runtime\_thriller }\OtherTok{=} \FunctionTok{mean}\NormalTok{(movies\_thrillerb}\SpecialCharTok{$}\NormalTok{runtime, }\AttributeTok{na.rm =}\NormalTok{ T)}
\NormalTok{n }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(movies\_thrillerb}\SpecialCharTok{$}\NormalTok{runtime))}
\NormalTok{sd\_thriller }\OtherTok{=} \FunctionTok{sd}\NormalTok{(movies\_thrillerb}\SpecialCharTok{$}\NormalTok{runtime, }\AttributeTok{na.rm =}\NormalTok{ T)}
\NormalTok{se\_thriller }\OtherTok{=}\NormalTok{ sd\_thriller}\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{z\_value }\OtherTok{=} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{)}

\NormalTok{lowerbound }\OtherTok{=}\NormalTok{ mean\_runtime\_thriller}\SpecialCharTok{{-}}\NormalTok{z\_value }\SpecialCharTok{*}\NormalTok{ se\_thriller}
\NormalTok{upperbound }\OtherTok{=}\NormalTok{ mean\_runtime\_thriller}\SpecialCharTok{+}\NormalTok{z\_value }\SpecialCharTok{*}\NormalTok{ se\_thriller}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(lowerbound,upperbound))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 102.1602 110.1180
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Methode =} \FunctionTok{c}\NormalTok{(}\StringTok{"a"}\NormalTok{,}\StringTok{"b"}\NormalTok{),}
  \AttributeTok{Lower =} \FunctionTok{c}\NormalTok{(movies\_thriller}\SpecialCharTok{$}\NormalTok{ci\_lower, lowerbound),}
  \AttributeTok{Upper =} \FunctionTok{c}\NormalTok{(movies\_thriller}\SpecialCharTok{$}\NormalTok{ci\_upper, upperbound)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Methode    Lower    Upper
## 1       a 100.5517 109.8965
## 2       b 102.1602 110.1180
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{interval\_a }\OtherTok{=}\NormalTok{ movies\_thriller}\SpecialCharTok{$}\NormalTok{ci\_upper }\SpecialCharTok{{-}}\NormalTok{ movies\_thriller}\SpecialCharTok{$}\NormalTok{ci\_lower}
\NormalTok{interval\_b }\OtherTok{=}\NormalTok{ upperbound}\SpecialCharTok{{-}}\NormalTok{lowerbound}

\NormalTok{interval\_a }\SpecialCharTok{\textgreater{}}\NormalTok{ interval\_b}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\textbf{Your Answer:}

When runtime is 0 in the dataset this is actually a NA, because a movie
can not have 0 run time. When taking this into account we come to the
conclusion that the interval of a {[}100.55,109.90{]} is bigger than the
interval of b {[}102.16,110.12{]}.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Using an appropriate five-step procedure, set up a test for the null
  hypothesis that the variance of runtime equals \(500\). Clearly state
  your null hypothesis, alternative hypothesis your test statistic, your
  critical value, and your conclusion. \textbf{[2 points]}
\item
  For the validity of your test in 2a, what assumption about the
  distribution of revenue needs to hold? Make an appropriate plot to
  test this assumption. What do you conclude? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sample\_var }\OtherTok{=} \FunctionTok{var}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{runtime, }\AttributeTok{na.rm =}\NormalTok{ T)}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{runtime))                }
\NormalTok{H0 }\OtherTok{=} \DecValTok{500}
\NormalTok{chi\_square }\OtherTok{=}\NormalTok{ ((n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{sample\_var)}\SpecialCharTok{/}\NormalTok{H0}
\NormalTok{a }\OtherTok{=} \FloatTok{0.05}
\NormalTok{critl }\OtherTok{=} \FunctionTok{qchisq}\NormalTok{(a}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{)}
\NormalTok{crith }\OtherTok{=} \FunctionTok{qchisq}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{a}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n}\DecValTok{{-}1}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (chi\_square}\SpecialCharTok{\textless{}}\NormalTok{critl}\SpecialCharTok{|}\NormalTok{chi\_square}\SpecialCharTok{\textgreater{}}\NormalTok{crith)\{}
\NormalTok{  conc }\OtherTok{=} \StringTok{"reject H0"}
\NormalTok{\}}\ControlFlowTok{else}\NormalTok{\{}
\NormalTok{  conc }\OtherTok{=} \StringTok{"accept H0"}
\NormalTok{\}}
\NormalTok{conc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "reject H0"
\end{verbatim}

\textbf{Your Answer:} step 1: cleary state H0 and HA step 2: computation
of the sample variance and length step 3: identify the test statistics
step 4: create critical values step 5: conclude H0, the variance of the
runtime is 500 HA, th variance of the runtime in not 500 test statistics
are: H0 =500 and chi\_square = ((n-1)\emph{sample\_var)/H0 Conclusion:
reject H0, since the variance is significantly different from 500 }step
b*

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{runtime)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-19-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{runtime)}
\FunctionTok{qqline}\NormalTok{(movies4}\SpecialCharTok{$}\NormalTok{runtime, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-19-2.pdf}}

\textbf{Your Answer:} For the chi square test to be valid, the runtime
must be normally distributed.

Based on the Plot, the runtime is not normally distributed, as there is
a slight left- and right tail deviation and an overall S-shape. This
means that the chi square test is not valid.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  There is an argument going on in the movie studio. \emph{Bob} claims
  that they should make higher-quality movies, as this will bring in
  more profits. \emph{Chantal} disagrees. She tells Bob that mediocre
  movies bring in the most profits. You are asked to advise on who is
  right.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new variable called vote\_average\_rounded. Make sure this
  variable is the same as vote\_average, but without any decimals (i.e.,
  a 6.3 becomes a 6, a 8.7 an 8, etc.). Display a histogram of
  vote\_average\_rounded. \textbf{[2 points]}
\item
  Create a scatter plot with vote\_average\_rounded on the x axis and
  the mean of profits within each category of vote\_average\_rounded on
  the y-axis. Make sure it has an appropriate title, and appropriate
  titles and labels for the x- and y-axis. At which rating of movies are
  profits the highest? \textbf{[3 points]}
\item
  Recreate the scatter plot with year on the x axis and mean\_profits on
  the y-axis, but now add bars around each point, indicating the 95\%
  confidence interval. \textbf{[3 points]}
\item
  Write an advice to settle the argument between Bob and Chantal.
  \textbf{[4 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{movies4 }\OtherTok{\textless{}{-}}\NormalTok{ movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{vote\_average\_rounded =} \FunctionTok{floor}\NormalTok{(vote\_average))}

\FunctionTok{ggplot}\NormalTok{(movies4, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{ vote\_average\_rounded)) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{10}\NormalTok{, }\AttributeTok{by =} \DecValTok{1}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-20-1.pdf}}

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies\_mean\_per\_vote }\OtherTok{\textless{}{-}}\NormalTok{ movies4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(vote\_average\_rounded) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Mean\_profit\_per\_vote =} \FunctionTok{mean}\NormalTok{(profit\_in\_millions))}

\FunctionTok{ggplot}\NormalTok{(movies\_mean\_per\_vote, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ vote\_average\_rounded, }\AttributeTok{y=}\NormalTok{ Mean\_profit\_per\_vote))}\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{10}\NormalTok{, }\AttributeTok{by =} \DecValTok{1}\NormalTok{), }\AttributeTok{minor\_breaks =}\NormalTok{ F)}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{50}\NormalTok{, }\DecValTok{250}\NormalTok{, }\DecValTok{25}\NormalTok{), }\AttributeTok{limits =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{25}\NormalTok{,}\DecValTok{250}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Average vote"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Profit in millions"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Average profit per rating"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-21-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies\_mean\_per\_vote[}\DecValTok{8}\NormalTok{,}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   Mean_profit_per_vote
##                  <dbl>
## 1                 241.
\end{verbatim}

\textbf{Your Answer:}

Movies rated with an 8 earn the highest profit, on average the profit is
241.18 million euro. \emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_profit\_per\_year }\OtherTok{\textless{}{-}}\NormalTok{ movies4}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(release\_year)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_profit\_per\_year =} \FunctionTok{mean}\NormalTok{(profit\_in\_millions),}
            \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(profit\_in\_millions),}
            \AttributeTok{se =}\NormalTok{ sd }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n),}
            \AttributeTok{t\_value =} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n}\DecValTok{{-}1}\NormalTok{),}
            \AttributeTok{lowerbound =}\NormalTok{ mean\_profit\_per\_year }\SpecialCharTok{{-}}\NormalTok{ t\_value }\SpecialCharTok{*}\NormalTok{ se,}
            \AttributeTok{upperbound =}\NormalTok{ mean\_profit\_per\_year }\SpecialCharTok{+}\NormalTok{ t\_value }\SpecialCharTok{*}\NormalTok{ se,}
            \AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(mean\_profit\_per\_year, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ release\_year,}\AttributeTok{y =}\NormalTok{ mean\_profit\_per\_year))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{1990}\NormalTok{,}\DecValTok{2016}\NormalTok{, }\AttributeTok{by =} \DecValTok{2}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{50}\NormalTok{,}\DecValTok{350}\NormalTok{, }\AttributeTok{by =} \DecValTok{50}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Release year"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Profit in million euro"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Mean profit per year with 95\% confidence interval"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_errorbar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{ymin =}\NormalTok{ lowerbound,}
                    \AttributeTok{ymax =}\NormalTok{ upperbound))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment11_files/figure-latex/unnamed-chunk-22-1.pdf}}

\textbf{Your Answer:}

The scatterplot shows the mean and the corresponding confidence interval
per year.We can conclude out of the plot that some years have a bigger
interval than others.

\emph{step d}

\textbf{Your Answer:} Bob and Chantal argued about which movies made the
biggest profit. Bob thought that high-quality movies made a bigger
profit, while Chantal argued that mediocre movies led to higher profits.
Chantal says that movies with a rating of around 5 or 6 will lead to the
highest profit, and Bob said that movies with higher quality, a rating
of around 7-8 or higher, will lead to higher profits. Upon examining the
data, the majority of movies have a rating of around 6. However, upon
analyzing the mean profit of movies with a rating of 6, we can conclude
that it is significantly lower than that of movies with a rating of 8.
Movies with a rating of 6 have around 60 million profit, while movies
with a rating of 8 have a profit of 240 million. So to give the movie
studio an advise is to focus on higher quality movies and listen to Bob.

\section{Week 4}\label{week-4}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  There is another argument going on in the movie studio. \emph{Bob}
  claims that production budgets are getting out of hand, and that the
  studio should focus on making cheaper movies. \emph{Chantal}
  disagrees. She tells Bob that ``Every dollar we spend on movie
  production is more than offset by the increase in movie profits'\,'.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Set up a regression model to test Chantal's claim, and estimate it.
  That is, estimate:
  \[\text{Profits}_i=\beta_0+\beta_1 \text{Budget}_i +\varepsilon_i.\]
  Print a summary of your estimated model. \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Test for the null hypothesis that \(\beta_1 \geq 0\). Report the
  p-value and state your conclusion. \textbf{[2 points]}
\item
  Next, estimate the model
  \[\text{Log Profits}_i=\beta_0+\beta_1 \text{Log Budget}_i +\varepsilon_i.\]
  When creating the variables Log Profits and Log Budget, make sure that
  movies with a Revenue or Budget of zero are assigned the value ``NA''.
  Print a summary of your estimated model \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Which model has better fit? The level-level model or the log-log
  model? Explain. \textbf{[2 points]}
\item
  Who do you think is correct? Bob or Chantal? What would you advise the
  movie studio to do? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step g}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Make a plot with a 95\% confidence interval with the mean log of
  budget on the y-axis, and whether the first actor of the movie is male
  or female on the x-axis. What do you conclude? \textbf{[2 points]}
\item
  Estimate the following simple OLS model:
  \(log(budget)_i=\beta_0+\beta_1 \text(FirstActorMale)_i + \varepsilon_i.\)
  Is the estimated coefficient for \(\beta_1\) significantly different
  from zero? How do you interpret its estimate, and how does this relate
  to your conclusion in 2a? \textbf{[2 points]}
\item
  Now, have a close look at your data frame. Can you find any instances
  of male first actors who are wrongly labeled as being female, or vice
  versa? What would such mislabelling mean for the coefficient you
  estimated under 2b? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\section{Week 5}\label{week-5}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  Create a plot of the mean profits by month of release. Do you see any
  indication that month of release matters to the profits of the movie?
  \textbf{[2 points]}
\item
  Estimate an OLS model which has as dependent variable the log of
  profits of a movie, and as independent variable the log of budget, a
  dummy for whether the movie was released in english or not, and a
  linear term for the month of release. Show a summary of the resulting
  model and interpret each coefficient. \textbf{[4 points]}
\item
  Test for the hypothesis that the coefficient that belongs to month of
  release is zero. \textbf{[2 points]}
\item
  Based on your plot in a.) do you consider the choice that month of
  release enters the model linearly under b.) reasonable? Estimate a
  specification that allows for a more flexible curve. In this new
  specification, test for the null hypothesis that month of release does
  not impact profits. This might require testing multiple terms at once.
  \textbf{[4 points]}
\item
  One executive at the studio wants to time the release of the movie to
  a specific month of the year such that they can maximize revenue.
  Based on your model under d.), What would you advise the movie studio
  regarding the timing of the release of the movie? \textbf{[2 points]}
\end{enumerate}

The movie studio that you work at is releasing a new movie in 2026. It
will be an English-spoken Thriller movie with a budget of 40,000,0000.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Estimate a model that is able to predict the revenue of this movie.
  Give its predicted revenue and include a 99\% prediction interval.
  \textbf{[6 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}


\end{document}
